blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    # Bir üste eklemek daha mı mantıklı? bunu nasıl anlıyor ''->index users'a nasıl geçiyor
    path('users/', include('users.urls')),
]

blogs/urls.py
"""Descripe Urls pattern for blogs"""

from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('<int:post_id>/', views.post, name='post'),
    path('new_post/', views.new_post, name='new_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

users/urls.py
"""Defined URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Default auth urls include
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    """."""

    title = models.CharField(max_length=200)
    #title = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    """
    Ve bu?
    def __str__(self):
        #Return string BlogPost#docstring
        if len(self.text) < 50:
            return self.text
        return f"{self.text[:50]}..."
    """

"""
Bunlar ne ayak
class Meta:
    #verbose_name_plural = 'posts'
    
    def __str__(self):
        #Return string BlogPost#docstring
        if len(self.text) < 50:
            return self.text
        return f"{self.text[:50]}..."
"""

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from . models import BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'text': ''}

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

# .'tanın bitişik olup olmaması birşey değiştirmiyor sanırım.
from .models import BlogPost
from .forms import BlogForm

def index(request):
    """Blog projesi için home page"""
    blog_post = BlogPost.objects.order_by('date_added')
    context = {'index': blog_post}
    return render(request, 'blogs/index.html', context)

def post(request, post_id):
    """Tek bir postu gösterir"""
    #post = BlogPost.objects.get(id=post_id)
    post = get_object_or_404(BlogPost, id=post_id)
    context = {'post': post}
    return render(request, 'blogs/post.html', context)

@login_required
def new_post(request):
    """Add new post"""
    if request.method != 'POST':
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)
        if form.is_valid():
            #form.save()
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:index')
    # Uyarılar hangisi sayesinde çıkıyor?(ör boş form submit)
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    """Edit an exist post"""
    post = BlogPost.objects.get(id=post_id)
    #post = BlogPost.objects.filter(owner=request.user).order_by('date_added')
    #post = BlogPost.objects.filter(owner=request.user)

    if post.owner != request.user:
        raise Http404
        #return redirect('blogs:new_post')

    if request.method != 'POST':
        #form = BlogForm(data=request.GET)#neden böyle değilde aşağıdaki gibi
        form = BlogForm(instance=post)
    else:
        form = BlogForm(instance=post, data=request.POST)
        if form.is_valid:
            form.save()
            return redirect('blogs:post', post_id=post.id)
            #return redirect('blogs:post', post_id)
    context = {'form': form, 'post': post}
    return render(request, 'blogs/edit_post.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register new user"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()

            login(request, new_user)
            return redirect('blogs:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
        initial-scale=1, shrink-to-fit=no">
    <title>Blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'blogs:index' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" 
            data-target="#navbarCollapse" aria-controls="navbarCollapse" 
            aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:login' %}">
                        Admin Site
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text"}">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>
        <a href="{% url 'blogs:post' post.id %}">{{ post.title }}</a>
    </p>
    <p>Edit post:</p>
    <form action="{% url 'blogs:edit_post' post.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Bu bir blog sitesidir.</h1>
        <p class="lead">...................................................</p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

{% block content %}
    <h1>All Blogs order_by(date)</h1>
    <h3><a href="{% url 'blogs:new_post' %}">Add a new post</a></h3>
    <ul>
        {% for b in index %}
            <li><h3>
                <a href="{% url 'blogs:post' b.id %}">{{ b.title }}</a>
            </h3></li>
            {% comment %}<p>{{ b.text[:50] }}</p>{% endcomment %}
        {% empty %}
            <li><h3>No post have been added yet.</h3></li>
        {% endfor %}
    </ul>
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>Add a new post:</p>

    <form action="{% url 'blogs:new_post' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add post</button>
    </form>
{% endblock content %}

blogs/templates/blogs/post.html
{% extends "blogs/base.html" %}
{% block page_header %}
    <h3>{{ post.title }}</h3>
{% endblock page_header %}

{% block content %}
    <div class="card mb-3">
        <h4 class="card-header">
            <p>
                {{ post.owner }}
                ,    
                {{ post.date_added|date:'M d/Y H:i' }}
            </p>
            {% if user.is_authenticated %}
                {% if post.owner == request.user %}
                    <small>
                        <a href="{% url 'blogs:edit_post' post.id %}">Edit post</a>
                    </small>
                {% endif %}
            {% endif %}
        </h4>
        <div class="card-body">
            {{ post.text|linebreaks }}
        </div>
    </div>
    <p>&nbsp; if empty çalışıyor mu? bak(empty post atılmıyor XD)</p>
    {% if empty %}
        <p>\0null''</p>
    {% endif %}
{% endblock content %}